[CREDENCIAL_SHEETS]
type = "service_account"
project_id = "luckjpa"
private_key_id = "d03832b0b9543166b50827ab3169b21f563e4cc1"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCW8RiWLONkcRJo
nuT2AvFZTTein/A0eoxnBUGUj1xzJGLVoFjj+QgSpoE/YsOxEvXXfpgOsI4zH5LC
vxatOyHkQGHsmacQCOHQNAqVz/96FV6Vs5ztsSuGWGPmpGPgsFuqmDWnX6mTZZ+e
9YFlpaI+2Qp5EKsndC2JpppCTpmtDs3P9Csv4MBCnJAvEuLk//TDcYvYetzU7HQD
hMKbe/1yewMc4L4G0oXVSnC3918NqeIceWzh2LDIN72l3uleE5MK3ZHN3goh6F+z
s6ZWI/BuWTR8cR8pIc+6xmj5AtkPy88T+X4kWdJUJH2du/5BTphlsNMkz4u66lEW
pF5K9mrPAgMBAAECggEAC4yWA4OawIgwTuX9gd9WxSz12VEgiXto+8b4rhvMCJlb
oJncw1C+L+Mil42AiK95NQxgKRuUPdAoJBOH8ihInxTYCUj2cfEkChC5UJ4yH468
BntQQhWgzW488pxYcgw8b1CnJk/ZA0iuznRdesASKnnj5cCDQAkRJOuk+PbXpliR
/xQLwgPr7oLU66Riomr+gElu4+rK2q582vAmexKb4XMG2OLmBIMmpha5OerYPkwS
ugNesNDYALWf6zqG9PrBUKPLj7RQrVjqkWwjegJT39gG4+xjX0ASo6VIpvfsbTAx
45WgFq1DRJtFVjA0ypZIaqPQbhljl5wog5tAj8RAzQKBgQDQunBGoZXWE/Ljyx59
2mhydrVDwA/wdJkIw3NYjuydkv+OExb8M6pVUYsbAkYrl+JmfQ8cRvN/4iPbNQl6
j44wz5Tz0uWaXG2iYyc/zceecv4tb7PFlPqqXNZtl1z8sU07Nt3xMo/ai4l5LGiW
QVQBBUkts1UURSkMVt4gxNCAiwKBgQC5IFYH7oQyoODJl+96xiZu3DHe6RVLnXFv
hFL+n9chYeYxEScPOWFB4rXmTqPkzquH3utC/YAXhfC6jRf+v1J+03bB/14CsMxz
1WaM95zhoh8uxU3Cw6JQfqPfssqFf573Uvxf4C8ApdZRLQQfpPMPm50Eexxkxmd8
w97Wut5jTQKBgQDE5+y9JPhWEVGkhVyJe33m5YeQl2IyA7zOoJty4rni2ObOn8Gi
QBcjD5775sRNoaYJ61ZS5bgWXz5WMA12GnEYKOuqrLy/RwyCEanYLgdvuamBMYxV
C3sBNj1u+0jUdWqXPuZXAMzmbZZNwpATlyNpJxRm0XOkgK39nwFDxoeviwKBgAVD
7i57kjb+bGZPc/hB+oXcrW5xorFr4PYTBWlIko3YgvuSSVIdh66gDBxo0DCJ0Ecl
B/v3ydThcl9b8/rC5k3FJfOOl9XrwWTqBOitgkDIo6po4jVP6yXu9CpAo5H4d0UB
jzwK3EtgbCAS77MWtfMTsfuWpNAY9IiP6Z6h4gFhAoGAZc0EuaJxbwTEzkjSyNxL
PdIZDlhbJWQOm57HtYqKK8ecDv79UJ7PlUIP5IAySjvJ6vEuQ/lcs+CdC61chvgu
uLCCQEFlsjWmBFiSz3su38gOFoke6zbMxqKe0v8xPV2hEfn39FodnjfYO1HdCDGd
bwEowd+kxSeo32GLTAElR70=
-----END PRIVATE KEY-----"""
client_email = "sheet-kuaramansear@luckjpa.iam.gserviceaccount.com"
client_id = "116403368841295841834"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheet-kuaramansear%40luckjpa.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
